### ISSUE TITLE
[1.16.5] Crash on multiplayer server the moment a player hits an entity

### ISSUE THREAD

**Issue by NighthowlerStudios** [cyanog3n/embellished_enchants_1.18.2#1]
```
        java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.func_70678_g(F)F
        at com.cyanogen.embellishedenchanting.enchantments.DeathsKnellEnchant.onAttack(DeathsKnellEnchant.java:88)
        at com.cyanogen.embellishedenchanting.EnchantmentEventHandler.onLivingAttack(EnchantmentEventHandler.java:31)
```

**Comment by NighthowlerStudios** [comment]
The method is marked as client only in minecraft's 1.16.5 codebase.
